config/routes.rb
Rails.application.routes.draw do
  root 'dishes#index'
  resources :ingredients
  resources :dishes
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  validates_presence_of :name, :address, :phone
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates_presence_of :description
  has_and_belongs_to_many :ingredients


end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :dishes
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :address, :phone, :email)
    end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all.order(:description)
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
    @ingredients = Ingredient.all.order(:description)
  end

  def restaurant_params
    params[:restaurant].permit(
        :name,
        :address,
        :phone,
        {:ingredient_ids => []}
    )
  end

  # GET /dishes/1/edit
  def edit
    @ingredients = Ingredient.all.order(:description)
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:description, :price, :preparationtime, :ingredient_ids => [])
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all.order(description: :asc)
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
  def formatar_hora(date)
    date.strftime("%H:%M")
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, id: :company_name, :class=> "form-control", :placeholder=>"Nome" %>
  </div>

  <div class="field">
    <%= form.text_field :address, id: :company_address, :class=> "form-control", :placeholder=>"Endereço" %>
  </div>

  <div class="field">
    <%= form.text_field :phone, id: :company_phone, :class=> "form-control", :placeholder=>"Telefone" %>
  </div>

  <div class="field">
    <%= form.text_field :email, id: :company_email, :class=> "form-control", :placeholder=>"Email" %>
  </div>

  <div style="margin-top: 20px;"class="actions">
    <%= form.submit :class=> "btn btn-success" %> |
    <%= link_to 'Voltar', companies_path, :class =>  "btn btn-secondary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="container" style="padding-top: 60px;">
<h1>Editar Restaurante</h1>

<%= render 'form', company: @company %>

</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row" style="padding-top: 15px;">

  <div class="col">
    <h1 style="font-size: 50px;">Restaurantes</h1>
  </div>
  <div class="col">
  <span style="padding-left: 400px; ">
<%= link_to 'Novo Restaurante', new_company_path, :class=> "btn btn-outline-success btn-lg" %>
  </span>
  </div>
</div>
<div class="row">
  <table class="table table-dark">
  <thead>
    <tr>
      <th style="font-size: 30px">Name</th>
      <th style="font-size: 30px">Address</th>
      <th style="font-size: 30px">Phone</th>
      <th style="font-size: 30px">Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td style="font-size: 20px"><%= company.name %></td>
        <td style="font-size: 20px"><%= company.address %></td>
        <td style="font-size: 20px"><%= company.phone %></td>
        <td style="font-size: 20px"><%= company.email %></td>
        <td><%= link_to 'Visualizar', company, :class=> "btn btn-warning" %></td>
        <td><%= link_to 'Editar', edit_company_path(company), :class=> "btn btn-primary" %></td>
        <td><%= link_to 'Excluir', company, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/companies/new.html.erb
<div class="container" style="padding-top: 60px;">
<h1>Cadastro de Restaurante</h1>

<%= render 'form', company: @company %>

</div>

app/views/companies/show.html.erb
<div class="container" style="padding-top: 60px;">
<p id="notice"><%= notice %></p>

<h2>
  <%= @company.name %>
</h2>
  <h6><%= @company.email %></h6>

<h4>
  <strong>Address:</strong>
  <%= @company.address %> |
  <strong>Phone:</strong>
  <%= @company.phone %>
</h4>


<%= link_to 'Edit', edit_company_path(@company), :class=> "btn btn-primary" %> |
<%= link_to 'Back', companies_path, :class=> "btn btn-info" %>
</div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true) do |form| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :description, id: :dish_description, :class=> "form-control", :placeholder=>"Descrição" %>
  </div>

  <div class="field">
    <%= form.text_field :price, id: :dish_price, :class=> "form-control", :placeholder=>"Valor" %>
  </div>

  <div class="field">
    <h3><%= form.label "Tempo de Preparação" %></h3>
    <%= form.time_select :preparationtime, id: :dish_preparationtime %>
  </div>

  <div class="field">
    <h3><%= form.label "Ingredientes" %></h3>
    <% @ingredients.each do |ingredient| %>

        <%= check_box_tag "dish[ingredient_ids][]", ingredient.id, @dish.ingredients.include?(ingredient) %>
        <%= ingredient.description %>
    <% end %>
  </div>

  <div style="margin-top: 20px;"class="actions">
    <%= form.submit :class=> "btn btn-success" %> |
    <%= link_to 'Voltar', dishes_path, :class =>  "btn btn-secondary" %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<div class="container" style="padding-top: 60px;">
<h1>Editar Prato</h1>

<%= render 'form', dish: @dish %>


</div>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row" style="padding-top: 15px;">

<div class="col">
<h1 style="font-size: 50px;">Pratos</h1>
</div>
<div class="col">
  <span style="padding-left: 400px; ">
<%= link_to 'Novo Prato', new_dish_path, :class=> "btn btn-outline-success btn-lg" %>
  </span>
</div>
</div>
<div class="row">
<table class="table table-dark">
  <thead>
    <tr>
      <th style="font-size: 30px">Valor</th>
      <th style="font-size: 30px">Descrição</th>
      <th style="font-size: 25px">Tempo de Preparação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td style="font-size: 20px">R<%= number_to_currency(dish.price) %></td>
        <td style="font-size: 20px"><%= dish.description %></td>
        <td style="text-align: center; font-size: 20px"><%= formatar_hora dish.preparationtime %></td>
        <td><%= link_to 'Visualizar', dish, :class=> "btn btn-warning" %></td>
        <td><%= link_to 'Editar', edit_dish_path(dish), :class=> "btn btn-info"%></td>
        <td><%= link_to 'Excluir', dish, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/dishes/new.html.erb
<div class="container" style="padding-top: 60px;">
<h1>Cadastro de Prato</h1>

<%= render 'form', dish: @dish %>

</div>

app/views/dishes/show.html.erb
<div class="container" style="padding-top: 60px;">
<p id="notice"><%= notice %></p>

<h6>
  <strong>Description:</strong>
  <%= @dish.description %>
</h6>

<p-h6>
  <strong>Price:</strong>
  <%= @dish.price %>
</p-h6>

<h6>
  <strong>Preparationtime:</strong>
  <%= @dish.preparationtime %>
</h6>


<p>
  <strong>Ingredientes:</strong><br>
  <% @dish.ingredients.order(:description).each do |ingredient| %>
    <span class="btn btn-info disabled">
    <%= ingredient.description %>
    </span>
    <% end %>
</p>

<%= link_to 'Editar', edit_dish_path(@dish), :class=> "btn btn-primary" %> |
<%= link_to 'Voltar', dishes_path, :class=> "btn btn-info" %>
</div>

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="margin-top: 30px;">
    <%= form.text_field :description, id: :ingredient_description, :class=> "form-control", :placeholder=>"Descrição" %>
  </div>

  <div style="margin-top: 20px;"class="actions">
    <%= form.submit :class=> "btn btn-success" %> |
    <%= link_to 'Voltar', ingredients_path, :class =>  "btn btn-secondary" %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<div class="container" style="padding-top: 60px;">
<h1>Editar Ingrediente</h1>

<%= render 'form', ingredient: @ingredient %>
</div>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row" style="padding-top: 15px;">

  <div class="col">
    <h1 style="font-size: 50px;">Ingredientes</h1>
  </div>
  <div class="col">
  <span style="padding-left: 400px; ">
<%= link_to 'Novo Ingrediente', new_ingredient_path, :class=> "btn btn-outline-success btn-lg" %>
  </span>
  </div>
</div>


  <ul class="list-group">
    <% @ingredients.each do |ingredient| %>
      <li class="list-group-item" style="background-color: #212529; border-style: solid; border-color: white; margin-right: 600px;">
      <%= link_to ingredient.description , ingredient, :class=> "btn btn-warning"  %>
        <a data-confirm="Deseja Realmente Excluir?" class="close" data-method="delete" href="/ingredients/<%=ingredient.id%>">
          <span aria-hidden="true">&times;</span>
        </a>
      </li>
    <% end %>
  </ul>

app/views/ingredients/new.html.erb
<div class="container" style="padding-top: 60px;">
<h1>Cadastro de Ingrediente</h1>

<%= render 'form', ingredient: @ingredient %>


</div>

app/views/ingredients/show.html.erb
<div class="container" style="padding-top: 60px;">
<p id="notice"><%= notice %></p>


  <h4><strong>Nome:</strong>
  <%= @ingredient.description %>
  </h4>

<%= link_to 'Editar', edit_ingredient_path(@ingredient), :class=> "btn btn-primary"  %>

<%= link_to 'Back', ingredients_path, :class=> "btn btn-info"%>
</div>

app/views/layouts/_menu.html.erb
<nav class=" menu navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link btn btn-light" style="margin-right: 15px;" href="<%=root_path %>">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-light" style="margin-right: 15px;" href="<%=dishes_path %>">Pratos <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-light" style="margin-right: 15px;" href="<%=companies_path%>">Restaurante <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-light" href="<%=ingredients_path%>">Ingredientes <span class="sr-only">(current)</span></a>
      </li>


    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurante</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/menu' %>
  <div class="row">
  <div class="container">
    <%= yield %>
  </div>
  </div>
  </body>
</html>